// Call-home (connection-reversal) contract for a Curlix Connector.
//
// WHY THIS SHAPE: a connector that runs inside a customer environment must NOT expose any
// inbound port (enterprises only allow egress). So the connector DIALS OUT to the SaaS and
// holds a single long-lived bidirectional stream open. The SaaS pushes WorkAssignments DOWN
// that already-open stream; the connector executes locally and streams WorkEvents back UP.
//
// Today the same connector binary can run anywhere (sidecar / SaaS-side) and "call home" to
// the gateway. Tomorrow it is installed in the customer account with a local read-only IAM
// role — no contract change, just a different deployment location.
//
// Transport: mTLS is the hardened path. The connector first calls `Enroll` over a server-TLS
// channel using a one-time enrollment token to obtain a client certificate whose SAN encodes
// its identity (spiffe://curlix.connector/tenant/<tenant>/connector/<id>), then opens `Connect`
// with that client cert. Bearer-token-over-edge-TLS remains supported for non-mTLS deployments.
// The browser never speaks this — the SaaS chat API bridges dispatched runs to the UI over SSE.
//
// CONTRACT: this is a versioned service boundary (the Skybridge Gateway API). The `v1` in the
// package is part of the wire identity. Only backward-compatible (additive) changes are allowed
// within `v1`; field numbers are permanent (use `reserved` when removing one); breaking changes go
// in a new `curlix.connector.v2` package. NOTE: this contract imports `curlix.agent.v1`, so a
// breaking change there breaks this too. CI (`buf breaking`) enforces both. See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: curlix/connector/v1/connector_gateway.proto

package connectorv1

import (
	v1 "github.com/curlix-io/skybridge/internal/genpb/curlix/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // one-time secret minted by an operator
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                      // must match the token's bound tenant
	ConnectorId     string                 `protobuf:"bytes,3,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`             // must match the token's bound connector
	CsrPem          string                 `protobuf:"bytes,4,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                            // PEM-encoded PKCS#10 CSR (connector keeps the private key)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem string                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // signed leaf cert (identity in SAN URI)
	CaBundlePem   string                 `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`       // CA chain the connector trusts for the gateway
	NotAfterUnix  int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`   // cert expiry (connector re-enrolls before this)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EnrollResponse) GetCaBundlePem() string {
	if x != nil {
		return x.CaBundlePem
	}
	return ""
}

func (x *EnrollResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`          // organization id this connector serves
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // stable connector instance id
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // connector build version (for upgrade/telemetry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Register) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMillis    int64                  `protobuf:"varint,1,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

// One agent event produced by a dispatched run, tagged with its run_id.
type WorkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Event         *v1.AgentEvent         `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkEvent) Reset() {
	*x = WorkEvent{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkEvent) ProtoMessage() {}

func (x *WorkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkEvent.ProtoReflect.Descriptor instead.
func (*WorkEvent) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *WorkEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkEvent) GetEvent() *v1.AgentEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type ConnectorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ConnectorMessage_Register
	//	*ConnectorMessage_WorkEvent
	//	*ConnectorMessage_Heartbeat
	Msg           isConnectorMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorMessage) Reset() {
	*x = ConnectorMessage{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorMessage) ProtoMessage() {}

func (x *ConnectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorMessage.ProtoReflect.Descriptor instead.
func (*ConnectorMessage) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectorMessage) GetMsg() isConnectorMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ConnectorMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*ConnectorMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ConnectorMessage) GetWorkEvent() *WorkEvent {
	if x != nil {
		if x, ok := x.Msg.(*ConnectorMessage_WorkEvent); ok {
			return x.WorkEvent
		}
	}
	return nil
}

func (x *ConnectorMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ConnectorMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isConnectorMessage_Msg interface {
	isConnectorMessage_Msg()
}

type ConnectorMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ConnectorMessage_WorkEvent struct {
	WorkEvent *WorkEvent `protobuf:"bytes,2,opt,name=work_event,json=workEvent,proto3,oneof"`
}

type ConnectorMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*ConnectorMessage_Register) isConnectorMessage_Msg() {}

func (*ConnectorMessage_WorkEvent) isConnectorMessage_Msg() {}

func (*ConnectorMessage_Heartbeat) isConnectorMessage_Msg() {}

type Registered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Registered) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// "Run this agent goal." Carries the resolved StartRun from the agent contract.
type WorkAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Start         *v1.StartRun           `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkAssignment) Reset() {
	*x = WorkAssignment{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAssignment) ProtoMessage() {}

func (x *WorkAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAssignment.ProtoReflect.Descriptor instead.
func (*WorkAssignment) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *WorkAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkAssignment) GetStart() *v1.StartRun {
	if x != nil {
		return x.Start
	}
	return nil
}

type CancelWork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWork) Reset() {
	*x = CancelWork{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWork) ProtoMessage() {}

func (x *CancelWork) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWork.ProtoReflect.Descriptor instead.
func (*CancelWork) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *CancelWork) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelWork) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMillis    int64                  `protobuf:"varint,1,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GatewayMessage_Registered
	//	*GatewayMessage_WorkAssignment
	//	*GatewayMessage_CancelWork
	//	*GatewayMessage_Ping
	Msg           isGatewayMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_connector_v1_connector_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayMessage) GetMsg() isGatewayMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GatewayMessage) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *GatewayMessage) GetWorkAssignment() *WorkAssignment {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_WorkAssignment); ok {
			return x.WorkAssignment
		}
	}
	return nil
}

func (x *GatewayMessage) GetCancelWork() *CancelWork {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_CancelWork); ok {
			return x.CancelWork
		}
	}
	return nil
}

func (x *GatewayMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isGatewayMessage_Msg interface {
	isGatewayMessage_Msg()
}

type GatewayMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type GatewayMessage_WorkAssignment struct {
	WorkAssignment *WorkAssignment `protobuf:"bytes,2,opt,name=work_assignment,json=workAssignment,proto3,oneof"`
}

type GatewayMessage_CancelWork struct {
	CancelWork *CancelWork `protobuf:"bytes,3,opt,name=cancel_work,json=cancelWork,proto3,oneof"`
}

type GatewayMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*GatewayMessage_Registered) isGatewayMessage_Msg() {}

func (*GatewayMessage_WorkAssignment) isGatewayMessage_Msg() {}

func (*GatewayMessage_CancelWork) isGatewayMessage_Msg() {}

func (*GatewayMessage_Ping) isGatewayMessage_Msg() {}

var File_curlix_connector_v1_connector_gateway_proto protoreflect.FileDescriptor

const file_curlix_connector_v1_connector_gateway_proto_rawDesc = "" +
	"\n" +
	"+curlix/connector/v1/connector_gateway.proto\x12\x13curlix.connector.v1\x1a\"curlix/agent/v1/agent_runner.proto\"\x93\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fconnector_id\x18\x03 \x01(\tR\vconnectorId\x12\x17\n" +
	"\acsr_pem\x18\x04 \x01(\tR\x06csrPem\"\x82\x01\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\tR\rclientCertPem\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\tR\vcaBundlePem\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\"d\n" +
	"\bRegister\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\",\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vunix_millis\x18\x01 \x01(\x03R\n" +
	"unixMillis\"U\n" +
	"\tWorkEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x121\n" +
	"\x05event\x18\x02 \x01(\v2\x1b.curlix.agent.v1.AgentEventR\x05event\"\xd7\x01\n" +
	"\x10ConnectorMessage\x12;\n" +
	"\bregister\x18\x01 \x01(\v2\x1d.curlix.connector.v1.RegisterH\x00R\bregister\x12?\n" +
	"\n" +
	"work_event\x18\x02 \x01(\v2\x1e.curlix.connector.v1.WorkEventH\x00R\tworkEvent\x12>\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1e.curlix.connector.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"+\n" +
	"\n" +
	"Registered\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"X\n" +
	"\x0eWorkAssignment\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12/\n" +
	"\x05start\x18\x02 \x01(\v2\x19.curlix.agent.v1.StartRunR\x05start\";\n" +
	"\n" +
	"CancelWork\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"'\n" +
	"\x04Ping\x12\x1f\n" +
	"\vunix_millis\x18\x01 \x01(\x03R\n" +
	"unixMillis\"\x9f\x02\n" +
	"\x0eGatewayMessage\x12A\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x1f.curlix.connector.v1.RegisteredH\x00R\n" +
	"registered\x12N\n" +
	"\x0fwork_assignment\x18\x02 \x01(\v2#.curlix.connector.v1.WorkAssignmentH\x00R\x0eworkAssignment\x12B\n" +
	"\vcancel_work\x18\x03 \x01(\v2\x1f.curlix.connector.v1.CancelWorkH\x00R\n" +
	"cancelWork\x12/\n" +
	"\x04ping\x18\x04 \x01(\v2\x19.curlix.connector.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg2\xc0\x01\n" +
	"\x10ConnectorGateway\x12Y\n" +
	"\aConnect\x12%.curlix.connector.v1.ConnectorMessage\x1a#.curlix.connector.v1.GatewayMessage(\x010\x01\x12Q\n" +
	"\x06Enroll\x12\".curlix.connector.v1.EnrollRequest\x1a#.curlix.connector.v1.EnrollResponseB\xed\x01\n" +
	"\x17com.curlix.connector.v1B\x15ConnectorGatewayProtoP\x01ZMgithub.com/curlix-io/skybridge/internal/genpb/curlix/connector/v1;connectorv1\xa2\x02\x03CCX\xaa\x02\x13Curlix.Connector.V1\xca\x02\x13Curlix\\Connector\\V1\xe2\x02\x1fCurlix\\Connector\\V1\\GPBMetadata\xea\x02\x15Curlix::Connector::V1b\x06proto3"

var (
	file_curlix_connector_v1_connector_gateway_proto_rawDescOnce sync.Once
	file_curlix_connector_v1_connector_gateway_proto_rawDescData []byte
)

func file_curlix_connector_v1_connector_gateway_proto_rawDescGZIP() []byte {
	file_curlix_connector_v1_connector_gateway_proto_rawDescOnce.Do(func() {
		file_curlix_connector_v1_connector_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_curlix_connector_v1_connector_gateway_proto_rawDesc), len(file_curlix_connector_v1_connector_gateway_proto_rawDesc)))
	})
	return file_curlix_connector_v1_connector_gateway_proto_rawDescData
}

var file_curlix_connector_v1_connector_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_curlix_connector_v1_connector_gateway_proto_goTypes = []any{
	(*EnrollRequest)(nil),    // 0: curlix.connector.v1.EnrollRequest
	(*EnrollResponse)(nil),   // 1: curlix.connector.v1.EnrollResponse
	(*Register)(nil),         // 2: curlix.connector.v1.Register
	(*Heartbeat)(nil),        // 3: curlix.connector.v1.Heartbeat
	(*WorkEvent)(nil),        // 4: curlix.connector.v1.WorkEvent
	(*ConnectorMessage)(nil), // 5: curlix.connector.v1.ConnectorMessage
	(*Registered)(nil),       // 6: curlix.connector.v1.Registered
	(*WorkAssignment)(nil),   // 7: curlix.connector.v1.WorkAssignment
	(*CancelWork)(nil),       // 8: curlix.connector.v1.CancelWork
	(*Ping)(nil),             // 9: curlix.connector.v1.Ping
	(*GatewayMessage)(nil),   // 10: curlix.connector.v1.GatewayMessage
	(*v1.AgentEvent)(nil),    // 11: curlix.agent.v1.AgentEvent
	(*v1.StartRun)(nil),      // 12: curlix.agent.v1.StartRun
}
var file_curlix_connector_v1_connector_gateway_proto_depIdxs = []int32{
	11, // 0: curlix.connector.v1.WorkEvent.event:type_name -> curlix.agent.v1.AgentEvent
	2,  // 1: curlix.connector.v1.ConnectorMessage.register:type_name -> curlix.connector.v1.Register
	4,  // 2: curlix.connector.v1.ConnectorMessage.work_event:type_name -> curlix.connector.v1.WorkEvent
	3,  // 3: curlix.connector.v1.ConnectorMessage.heartbeat:type_name -> curlix.connector.v1.Heartbeat
	12, // 4: curlix.connector.v1.WorkAssignment.start:type_name -> curlix.agent.v1.StartRun
	6,  // 5: curlix.connector.v1.GatewayMessage.registered:type_name -> curlix.connector.v1.Registered
	7,  // 6: curlix.connector.v1.GatewayMessage.work_assignment:type_name -> curlix.connector.v1.WorkAssignment
	8,  // 7: curlix.connector.v1.GatewayMessage.cancel_work:type_name -> curlix.connector.v1.CancelWork
	9,  // 8: curlix.connector.v1.GatewayMessage.ping:type_name -> curlix.connector.v1.Ping
	5,  // 9: curlix.connector.v1.ConnectorGateway.Connect:input_type -> curlix.connector.v1.ConnectorMessage
	0,  // 10: curlix.connector.v1.ConnectorGateway.Enroll:input_type -> curlix.connector.v1.EnrollRequest
	10, // 11: curlix.connector.v1.ConnectorGateway.Connect:output_type -> curlix.connector.v1.GatewayMessage
	1,  // 12: curlix.connector.v1.ConnectorGateway.Enroll:output_type -> curlix.connector.v1.EnrollResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_curlix_connector_v1_connector_gateway_proto_init() }
func file_curlix_connector_v1_connector_gateway_proto_init() {
	if File_curlix_connector_v1_connector_gateway_proto != nil {
		return
	}
	file_curlix_connector_v1_connector_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*ConnectorMessage_Register)(nil),
		(*ConnectorMessage_WorkEvent)(nil),
		(*ConnectorMessage_Heartbeat)(nil),
	}
	file_curlix_connector_v1_connector_gateway_proto_msgTypes[10].OneofWrappers = []any{
		(*GatewayMessage_Registered)(nil),
		(*GatewayMessage_WorkAssignment)(nil),
		(*GatewayMessage_CancelWork)(nil),
		(*GatewayMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_curlix_connector_v1_connector_gateway_proto_rawDesc), len(file_curlix_connector_v1_connector_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_curlix_connector_v1_connector_gateway_proto_goTypes,
		DependencyIndexes: file_curlix_connector_v1_connector_gateway_proto_depIdxs,
		MessageInfos:      file_curlix_connector_v1_connector_gateway_proto_msgTypes,
	}.Build()
	File_curlix_connector_v1_connector_gateway_proto = out.File
	file_curlix_connector_v1_connector_gateway_proto_goTypes = nil
	file_curlix_connector_v1_connector_gateway_proto_depIdxs = nil
}
