// Call-home (connection-reversal) contract for a Curlix Connector.
//
// WHY THIS SHAPE: a connector that runs inside a customer environment must NOT expose any
// inbound port (enterprises only allow egress). So the connector DIALS OUT to the SaaS and
// holds a single long-lived bidirectional stream open. The SaaS pushes WorkAssignments DOWN
// that already-open stream; the connector executes locally and streams WorkEvents back UP.
//
// Today the same connector binary can run anywhere (sidecar / SaaS-side) and "call home" to
// the gateway. Tomorrow it is installed in the customer account with a local read-only IAM
// role — no contract change, just a different deployment location.
//
// Transport: mTLS is the hardened path. The connector first calls `Enroll` over a server-TLS
// channel using a one-time enrollment token to obtain a client certificate whose SAN encodes
// its identity (spiffe://curlix.connector/tenant/<tenant>/connector/<id>), then opens `Connect`
// with that client cert. Bearer-token-over-edge-TLS remains supported for non-mTLS deployments.
// The browser never speaks this — the SaaS chat API bridges dispatched runs to the UI over SSE.
//
// CONTRACT: this is a versioned service boundary (the Skybridge Gateway API). The `v1` in the
// package is part of the wire identity. Only backward-compatible (additive) changes are allowed
// within `v1`; field numbers are permanent (use `reserved` when removing one); breaking changes go
// in a new `curlix.connector.v2` package. NOTE: this contract imports `curlix.agent.v1`, so a
// breaking change there breaks this too. CI (`buf breaking`) enforces both. See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: curlix/connector/v1/connector_gateway.proto

package connectorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorGateway_Connect_FullMethodName = "/curlix.connector.v1.ConnectorGateway/Connect"
	ConnectorGateway_Enroll_FullMethodName  = "/curlix.connector.v1.ConnectorGateway/Enroll"
)

// ConnectorGatewayClient is the client API for ConnectorGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectorGateway lives on the SaaS side. Connectors are CLIENTS that connect to it.
type ConnectorGatewayClient interface {
	// The connector opens this stream and keeps it open. Multiplexes many concurrent agent
	// runs over the one connection, keyed by run_id.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectorMessage, GatewayMessage], error)
	// Bootstrap mTLS: exchange a one-time enrollment token + CSR for a signed client cert.
	// Called over a server-TLS channel (no client cert yet). Single-use; the returned cert's
	// SAN binds the connector's tenant/connector identity for all later Connect calls.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type connectorGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorGatewayClient(cc grpc.ClientConnInterface) ConnectorGatewayClient {
	return &connectorGatewayClient{cc}
}

func (c *connectorGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectorMessage, GatewayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectorGateway_ServiceDesc.Streams[0], ConnectorGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectorMessage, GatewayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorGateway_ConnectClient = grpc.BidiStreamingClient[ConnectorMessage, GatewayMessage]

func (c *connectorGatewayClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, ConnectorGateway_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorGatewayServer is the server API for ConnectorGateway service.
// All implementations must embed UnimplementedConnectorGatewayServer
// for forward compatibility.
//
// ConnectorGateway lives on the SaaS side. Connectors are CLIENTS that connect to it.
type ConnectorGatewayServer interface {
	// The connector opens this stream and keeps it open. Multiplexes many concurrent agent
	// runs over the one connection, keyed by run_id.
	Connect(grpc.BidiStreamingServer[ConnectorMessage, GatewayMessage]) error
	// Bootstrap mTLS: exchange a one-time enrollment token + CSR for a signed client cert.
	// Called over a server-TLS channel (no client cert yet). Single-use; the returned cert's
	// SAN binds the connector's tenant/connector identity for all later Connect calls.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedConnectorGatewayServer()
}

// UnimplementedConnectorGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorGatewayServer struct{}

func (UnimplementedConnectorGatewayServer) Connect(grpc.BidiStreamingServer[ConnectorMessage, GatewayMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConnectorGatewayServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedConnectorGatewayServer) mustEmbedUnimplementedConnectorGatewayServer() {}
func (UnimplementedConnectorGatewayServer) testEmbeddedByValue()                          {}

// UnsafeConnectorGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorGatewayServer will
// result in compilation errors.
type UnsafeConnectorGatewayServer interface {
	mustEmbedUnimplementedConnectorGatewayServer()
}

func RegisterConnectorGatewayServer(s grpc.ServiceRegistrar, srv ConnectorGatewayServer) {
	// If the following call panics, it indicates UnimplementedConnectorGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorGateway_ServiceDesc, srv)
}

func _ConnectorGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectorGatewayServer).Connect(&grpc.GenericServerStream[ConnectorMessage, GatewayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorGateway_ConnectServer = grpc.BidiStreamingServer[ConnectorMessage, GatewayMessage]

func _ConnectorGateway_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorGatewayServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorGateway_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorGatewayServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorGateway_ServiceDesc is the grpc.ServiceDesc for ConnectorGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "curlix.connector.v1.ConnectorGateway",
	HandlerType: (*ConnectorGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _ConnectorGateway_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ConnectorGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "curlix/connector/v1/connector_gateway.proto",
}
