// Internal service-to-service contract for the Curlix read-only SRE agent.
//
// This is a DATA-PLANE / internal API, NOT the public product surface. The public
// surface stays REST + OpenAPI under /api/v1 (see .cursor/rules/00-rules.mdc). The
// browser never speaks gRPC directly; the FastAPI chat API bridges this stream to
// the UI over SSE.
//
// Transport: TLS terminated at the load balancer; the server binds insecure on the
// app port. Auth is carried in the gRPC `authorization` metadata (CLI/service token),
// identical trust model to /api/v1.
//
// CONTRACT: this is a versioned service boundary. The `v1` in the package is part of the wire
// identity. Only backward-compatible (additive) changes are allowed within `v1`; field numbers
// are permanent (use `reserved` when removing one); breaking changes go in a new `curlix.agent.v2`
// package served alongside `v1`. CI (`buf breaking`) enforces this. See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: curlix/agent/v1/agent_runner.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resolved caller identity. The chat API authenticates the human (cookie/bearer) and
// passes the already-resolved principal here; the runner does NOT re-run user auth,
// it trusts this internal envelope (the channel itself is service-authenticated).
type AgentIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	AwsAccountId   string                 `protobuf:"bytes,4,opt,name=aws_account_id,json=awsAccountId,proto3" json:"aws_account_id,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{0}
}

func (x *AgentIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AgentIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AgentIdentity) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AgentIdentity) GetAwsAccountId() string {
	if x != nil {
		return x.AwsAccountId
	}
	return ""
}

func (x *AgentIdentity) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type StartRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	MaxSteps      int32                  `protobuf:"varint,2,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"` // clamped to [1, 3] server-side
	Identity      *AgentIdentity         `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	StreamTokens  bool                   `protobuf:"varint,4,opt,name=stream_tokens,json=streamTokens,proto3" json:"stream_tokens,omitempty"` // when true, emit TokenDelta events as the model generates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRun) Reset() {
	*x = StartRun{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRun) ProtoMessage() {}

func (x *StartRun) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRun.ProtoReflect.Descriptor instead.
func (*StartRun) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{1}
}

func (x *StartRun) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *StartRun) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *StartRun) GetIdentity() *AgentIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *StartRun) GetStreamTokens() bool {
	if x != nil {
		return x.StreamTokens
	}
	return false
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRun) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AgentClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentClientMessage_Start
	//	*AgentClientMessage_Cancel
	Msg           isAgentClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentClientMessage) Reset() {
	*x = AgentClientMessage{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentClientMessage) ProtoMessage() {}

func (x *AgentClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentClientMessage.ProtoReflect.Descriptor instead.
func (*AgentClientMessage) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{3}
}

func (x *AgentClientMessage) GetMsg() isAgentClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentClientMessage) GetStart() *StartRun {
	if x != nil {
		if x, ok := x.Msg.(*AgentClientMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AgentClientMessage) GetCancel() *CancelRun {
	if x != nil {
		if x, ok := x.Msg.(*AgentClientMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isAgentClientMessage_Msg interface {
	isAgentClientMessage_Msg()
}

type AgentClientMessage_Start struct {
	Start *StartRun `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type AgentClientMessage_Cancel struct {
	Cancel *CancelRun `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

func (*AgentClientMessage_Start) isAgentClientMessage_Msg() {}

func (*AgentClientMessage_Cancel) isAgentClientMessage_Msg() {}

// Incremental model output for live "typing" UX. Raw model text (may be partial JSON);
// the structured timeline arrives via StepEvent / Tool* / RunFinished.
type TokenDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDelta) Reset() {
	*x = TokenDelta{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDelta) ProtoMessage() {}

func (x *TokenDelta) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDelta.ProtoReflect.Descriptor instead.
func (*TokenDelta) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{4}
}

func (x *TokenDelta) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TokenDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// One agent turn after the model response parsed: human title/status/description.
type StepEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	WillCallTool  bool                   `protobuf:"varint,5,opt,name=will_call_tool,json=willCallTool,proto3" json:"will_call_tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEvent) Reset() {
	*x = StepEvent{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEvent) ProtoMessage() {}

func (x *StepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEvent.ProtoReflect.Descriptor instead.
func (*StepEvent) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{5}
}

func (x *StepEvent) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *StepEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StepEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StepEvent) GetWillCallTool() bool {
	if x != nil {
		return x.WillCallTool
	}
	return false
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // JSON-encoded arguments object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{6}
}

func (x *ToolCall) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"` // JSON-encoded (already PII-redacted) tool output
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{7}
}

func (x *ToolResult) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ToolResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToolResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolResult) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Terminal event. Carries the full canonical AIAgentRunResponse as JSON so the caller
// reconstructs the exact same structured result the REST /run endpoint returns.
type RunFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  string                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFinished) Reset() {
	*x = RunFinished{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinished) ProtoMessage() {}

func (x *RunFinished) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinished.ProtoReflect.Descriptor instead.
func (*RunFinished) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{8}
}

func (x *RunFinished) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type AgentEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_Token
	//	*AgentEvent_Step
	//	*AgentEvent_ToolCall
	//	*AgentEvent_ToolResult
	//	*AgentEvent_Finished
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_agent_v1_agent_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_curlix_agent_v1_agent_runner_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetToken() *TokenDelta {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *AgentEvent) GetStep() *StepEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Step); ok {
			return x.Step
		}
	}
	return nil
}

func (x *AgentEvent) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *AgentEvent) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *AgentEvent) GetFinished() *RunFinished {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_Token struct {
	Token *TokenDelta `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type AgentEvent_Step struct {
	Step *StepEvent `protobuf:"bytes,2,opt,name=step,proto3,oneof"`
}

type AgentEvent_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,3,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type AgentEvent_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,4,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type AgentEvent_Finished struct {
	Finished *RunFinished `protobuf:"bytes,5,opt,name=finished,proto3,oneof"`
}

func (*AgentEvent_Token) isAgentEvent_Event() {}

func (*AgentEvent_Step) isAgentEvent_Event() {}

func (*AgentEvent_ToolCall) isAgentEvent_Event() {}

func (*AgentEvent_ToolResult) isAgentEvent_Event() {}

func (*AgentEvent_Finished) isAgentEvent_Event() {}

var File_curlix_agent_v1_agent_runner_proto protoreflect.FileDescriptor

const file_curlix_agent_v1_agent_runner_proto_rawDesc = "" +
	"\n" +
	"\"curlix/agent/v1/agent_runner.proto\x12\x0fcurlix.agent.v1\"\xb7\x01\n" +
	"\rAgentIdentity\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0eaws_account_id\x18\x04 \x01(\tR\fawsAccountId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x9c\x01\n" +
	"\bStartRun\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x1b\n" +
	"\tmax_steps\x18\x02 \x01(\x05R\bmaxSteps\x12:\n" +
	"\bidentity\x18\x03 \x01(\v2\x1e.curlix.agent.v1.AgentIdentityR\bidentity\x12#\n" +
	"\rstream_tokens\x18\x04 \x01(\bR\fstreamTokens\"#\n" +
	"\tCancelRun\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x84\x01\n" +
	"\x12AgentClientMessage\x121\n" +
	"\x05start\x18\x01 \x01(\v2\x19.curlix.agent.v1.StartRunH\x00R\x05start\x124\n" +
	"\x06cancel\x18\x02 \x01(\v2\x1a.curlix.agent.v1.CancelRunH\x00R\x06cancelB\x05\n" +
	"\x03msg\"4\n" +
	"\n" +
	"TokenDelta\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x95\x01\n" +
	"\tStepEvent\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\x0ewill_call_tool\x18\x05 \x01(\bR\fwillCallTool\"Y\n" +
	"\bToolCall\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"{\n" +
	"\n" +
	"ToolResult\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"2\n" +
	"\vRunFinished\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\tR\fresponseJson\"\xb2\x02\n" +
	"\n" +
	"AgentEvent\x123\n" +
	"\x05token\x18\x01 \x01(\v2\x1b.curlix.agent.v1.TokenDeltaH\x00R\x05token\x120\n" +
	"\x04step\x18\x02 \x01(\v2\x1a.curlix.agent.v1.StepEventH\x00R\x04step\x128\n" +
	"\ttool_call\x18\x03 \x01(\v2\x19.curlix.agent.v1.ToolCallH\x00R\btoolCall\x12>\n" +
	"\vtool_result\x18\x04 \x01(\v2\x1b.curlix.agent.v1.ToolResultH\x00R\n" +
	"toolResult\x12:\n" +
	"\bfinished\x18\x05 \x01(\v2\x1c.curlix.agent.v1.RunFinishedH\x00R\bfinishedB\a\n" +
	"\x05event2_\n" +
	"\vAgentRunner\x12P\n" +
	"\bRunAgent\x12#.curlix.agent.v1.AgentClientMessage\x1a\x1b.curlix.agent.v1.AgentEvent(\x010\x01B\xcc\x01\n" +
	"\x13com.curlix.agent.v1B\x10AgentRunnerProtoP\x01ZEgithub.com/curlix-io/skybridge/internal/genpb/curlix/agent/v1;agentv1\xa2\x02\x03CAX\xaa\x02\x0fCurlix.Agent.V1\xca\x02\x0fCurlix\\Agent\\V1\xe2\x02\x1bCurlix\\Agent\\V1\\GPBMetadata\xea\x02\x11Curlix::Agent::V1b\x06proto3"

var (
	file_curlix_agent_v1_agent_runner_proto_rawDescOnce sync.Once
	file_curlix_agent_v1_agent_runner_proto_rawDescData []byte
)

func file_curlix_agent_v1_agent_runner_proto_rawDescGZIP() []byte {
	file_curlix_agent_v1_agent_runner_proto_rawDescOnce.Do(func() {
		file_curlix_agent_v1_agent_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_curlix_agent_v1_agent_runner_proto_rawDesc), len(file_curlix_agent_v1_agent_runner_proto_rawDesc)))
	})
	return file_curlix_agent_v1_agent_runner_proto_rawDescData
}

var file_curlix_agent_v1_agent_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_curlix_agent_v1_agent_runner_proto_goTypes = []any{
	(*AgentIdentity)(nil),      // 0: curlix.agent.v1.AgentIdentity
	(*StartRun)(nil),           // 1: curlix.agent.v1.StartRun
	(*CancelRun)(nil),          // 2: curlix.agent.v1.CancelRun
	(*AgentClientMessage)(nil), // 3: curlix.agent.v1.AgentClientMessage
	(*TokenDelta)(nil),         // 4: curlix.agent.v1.TokenDelta
	(*StepEvent)(nil),          // 5: curlix.agent.v1.StepEvent
	(*ToolCall)(nil),           // 6: curlix.agent.v1.ToolCall
	(*ToolResult)(nil),         // 7: curlix.agent.v1.ToolResult
	(*RunFinished)(nil),        // 8: curlix.agent.v1.RunFinished
	(*AgentEvent)(nil),         // 9: curlix.agent.v1.AgentEvent
}
var file_curlix_agent_v1_agent_runner_proto_depIdxs = []int32{
	0, // 0: curlix.agent.v1.StartRun.identity:type_name -> curlix.agent.v1.AgentIdentity
	1, // 1: curlix.agent.v1.AgentClientMessage.start:type_name -> curlix.agent.v1.StartRun
	2, // 2: curlix.agent.v1.AgentClientMessage.cancel:type_name -> curlix.agent.v1.CancelRun
	4, // 3: curlix.agent.v1.AgentEvent.token:type_name -> curlix.agent.v1.TokenDelta
	5, // 4: curlix.agent.v1.AgentEvent.step:type_name -> curlix.agent.v1.StepEvent
	6, // 5: curlix.agent.v1.AgentEvent.tool_call:type_name -> curlix.agent.v1.ToolCall
	7, // 6: curlix.agent.v1.AgentEvent.tool_result:type_name -> curlix.agent.v1.ToolResult
	8, // 7: curlix.agent.v1.AgentEvent.finished:type_name -> curlix.agent.v1.RunFinished
	3, // 8: curlix.agent.v1.AgentRunner.RunAgent:input_type -> curlix.agent.v1.AgentClientMessage
	9, // 9: curlix.agent.v1.AgentRunner.RunAgent:output_type -> curlix.agent.v1.AgentEvent
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_curlix_agent_v1_agent_runner_proto_init() }
func file_curlix_agent_v1_agent_runner_proto_init() {
	if File_curlix_agent_v1_agent_runner_proto != nil {
		return
	}
	file_curlix_agent_v1_agent_runner_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentClientMessage_Start)(nil),
		(*AgentClientMessage_Cancel)(nil),
	}
	file_curlix_agent_v1_agent_runner_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentEvent_Token)(nil),
		(*AgentEvent_Step)(nil),
		(*AgentEvent_ToolCall)(nil),
		(*AgentEvent_ToolResult)(nil),
		(*AgentEvent_Finished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_curlix_agent_v1_agent_runner_proto_rawDesc), len(file_curlix_agent_v1_agent_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_curlix_agent_v1_agent_runner_proto_goTypes,
		DependencyIndexes: file_curlix_agent_v1_agent_runner_proto_depIdxs,
		MessageInfos:      file_curlix_agent_v1_agent_runner_proto_msgTypes,
	}.Build()
	File_curlix_agent_v1_agent_runner_proto = out.File
	file_curlix_agent_v1_agent_runner_proto_goTypes = nil
	file_curlix_agent_v1_agent_runner_proto_depIdxs = nil
}
