// Internal service-to-service contract for the Curlix read-only SRE agent.
//
// This is a DATA-PLANE / internal API, NOT the public product surface. The public
// surface stays REST + OpenAPI under /api/v1 (see .cursor/rules/00-rules.mdc). The
// browser never speaks gRPC directly; the FastAPI chat API bridges this stream to
// the UI over SSE.
//
// Transport: TLS terminated at the load balancer; the server binds insecure on the
// app port. Auth is carried in the gRPC `authorization` metadata (CLI/service token),
// identical trust model to /api/v1.
//
// CONTRACT: this is a versioned service boundary. The `v1` in the package is part of the wire
// identity. Only backward-compatible (additive) changes are allowed within `v1`; field numbers
// are permanent (use `reserved` when removing one); breaking changes go in a new `curlix.agent.v2`
// package served alongside `v1`. CI (`buf breaking`) enforces this. See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: curlix/agent/v1/agent_runner.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRunner_RunAgent_FullMethodName = "/curlix.agent.v1.AgentRunner/RunAgent"
)

// AgentRunnerClient is the client API for AgentRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRunner executes a bounded, read-only multi-step SRE agent loop and streams
// its progress back to the caller. The RPC is bidirectional so the caller (the chat
// API) can inject control messages (cancel) while events stream out.
type AgentRunnerClient interface {
	// Bidirectional stream: the client first sends StartRun, then may send CancelRun.
	// The server streams AgentEvent messages until a terminal RunFinished is emitted.
	RunAgent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentClientMessage, AgentEvent], error)
}

type agentRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRunnerClient(cc grpc.ClientConnInterface) AgentRunnerClient {
	return &agentRunnerClient{cc}
}

func (c *agentRunnerClient) RunAgent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentClientMessage, AgentEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRunner_ServiceDesc.Streams[0], AgentRunner_RunAgent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentClientMessage, AgentEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRunner_RunAgentClient = grpc.BidiStreamingClient[AgentClientMessage, AgentEvent]

// AgentRunnerServer is the server API for AgentRunner service.
// All implementations must embed UnimplementedAgentRunnerServer
// for forward compatibility.
//
// AgentRunner executes a bounded, read-only multi-step SRE agent loop and streams
// its progress back to the caller. The RPC is bidirectional so the caller (the chat
// API) can inject control messages (cancel) while events stream out.
type AgentRunnerServer interface {
	// Bidirectional stream: the client first sends StartRun, then may send CancelRun.
	// The server streams AgentEvent messages until a terminal RunFinished is emitted.
	RunAgent(grpc.BidiStreamingServer[AgentClientMessage, AgentEvent]) error
	mustEmbedUnimplementedAgentRunnerServer()
}

// UnimplementedAgentRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRunnerServer struct{}

func (UnimplementedAgentRunnerServer) RunAgent(grpc.BidiStreamingServer[AgentClientMessage, AgentEvent]) error {
	return status.Error(codes.Unimplemented, "method RunAgent not implemented")
}
func (UnimplementedAgentRunnerServer) mustEmbedUnimplementedAgentRunnerServer() {}
func (UnimplementedAgentRunnerServer) testEmbeddedByValue()                     {}

// UnsafeAgentRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRunnerServer will
// result in compilation errors.
type UnsafeAgentRunnerServer interface {
	mustEmbedUnimplementedAgentRunnerServer()
}

func RegisterAgentRunnerServer(s grpc.ServiceRegistrar, srv AgentRunnerServer) {
	// If the following call panics, it indicates UnimplementedAgentRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRunner_ServiceDesc, srv)
}

func _AgentRunner_RunAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRunnerServer).RunAgent(&grpc.GenericServerStream[AgentClientMessage, AgentEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRunner_RunAgentServer = grpc.BidiStreamingServer[AgentClientMessage, AgentEvent]

// AgentRunner_ServiceDesc is the grpc.ServiceDesc for AgentRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "curlix.agent.v1.AgentRunner",
	HandlerType: (*AgentRunnerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunAgent",
			Handler:       _AgentRunner_RunAgent_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "curlix/agent/v1/agent_runner.proto",
}
