// Call-home (connection-reversal) contract for a Curlix Studio Agent.
//
// WHY THIS SHAPE: a Studio Agent runs next to the database (typically inside the customer network,
// egress-only). It must NOT expose an inbound port. So the agent DIALS OUT to the SaaS Studio
// Gateway and holds a single long-lived bidirectional stream open. The gateway leases query-execution
// sessions and pushes ExecuteAssignments DOWN that already-open stream; the agent runs the query
// locally (the DB connection never leaves the customer network), redacts PII locally, and streams
// SessionEvents (progress, redacted rows, result, audit) back UP. Many concurrent sessions multiplex
// over the one connection, keyed by session_id.
//
// This is the transport for the Studio execution tier (see docs/design/studio-agent-gateway.md).
// It deliberately mirrors curlix.connector.v1 (connection reversal + mTLS enrollment) and reuses the
// event-stream style of curlix.agent.v1 (terminal *_finished carries the canonical response JSON).
//
// Transport: mTLS is the hardened path. The agent first calls `Enroll` over a server-TLS channel with
// a one-time enrollment token to obtain a client certificate whose SAN encodes its identity
// (spiffe://curlix.studio-agent/tenant/<tenant>/agent/<id>), then opens `Connect` with that client
// cert. Bearer-token-over-edge-TLS remains supported for non-mTLS deployments. The browser never
// speaks this — the SaaS FastAPI app bridges live sessions to the UI over SSE / poll under /api/v1.
//
// CONTRACT: this is a versioned service boundary (the Studio Gateway API). The `v1` in the package is
// part of the wire identity. Only backward-compatible (additive) changes are allowed within `v1`;
// field numbers are permanent (use `reserved` when removing one); breaking changes go in a new
// `curlix.studiogateway.v2` package served alongside `v1`. CI (`buf breaking`) enforces this.
// See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: curlix/studiogateway/v1/studio_gateway.proto

package studiogatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StudioGateway_Connect_FullMethodName    = "/curlix.studiogateway.v1.StudioGateway/Connect"
	StudioGateway_Enroll_FullMethodName     = "/curlix.studiogateway.v1.StudioGateway/Enroll"
	StudioGateway_PreConnect_FullMethodName = "/curlix.studiogateway.v1.StudioGateway/PreConnect"
)

// StudioGatewayClient is the client API for StudioGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StudioGateway lives on the SaaS side. Studio Agents are CLIENTS that connect to it.
type StudioGatewayClient interface {
	// The agent opens this stream and keeps it open. Multiplexes many concurrent execution
	// sessions over the one connection, keyed by session_id.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, GatewayMessage], error)
	// Bootstrap mTLS: exchange a one-time enrollment token + CSR for a signed client cert.
	// Called over a server-TLS channel (no client cert yet). Single-use; the returned cert's
	// SAN binds the agent's tenant/agent identity for all later Connect calls.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// Cheap unary check the agent SHOULD call before opening the full Connect stream, mirroring
	// curlix.connector.v1.ConnectorGateway.PreConnect — see that RPC's comment and
	// docs/design/skybridge-masking-architecture.md §10.
	PreConnect(ctx context.Context, in *PreConnectRequest, opts ...grpc.CallOption) (*PreConnectResponse, error)
}

type studioGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewStudioGatewayClient(cc grpc.ClientConnInterface) StudioGatewayClient {
	return &studioGatewayClient{cc}
}

func (c *studioGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, GatewayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StudioGateway_ServiceDesc.Streams[0], StudioGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, GatewayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StudioGateway_ConnectClient = grpc.BidiStreamingClient[AgentMessage, GatewayMessage]

func (c *studioGatewayClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, StudioGateway_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studioGatewayClient) PreConnect(ctx context.Context, in *PreConnectRequest, opts ...grpc.CallOption) (*PreConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreConnectResponse)
	err := c.cc.Invoke(ctx, StudioGateway_PreConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudioGatewayServer is the server API for StudioGateway service.
// All implementations must embed UnimplementedStudioGatewayServer
// for forward compatibility.
//
// StudioGateway lives on the SaaS side. Studio Agents are CLIENTS that connect to it.
type StudioGatewayServer interface {
	// The agent opens this stream and keeps it open. Multiplexes many concurrent execution
	// sessions over the one connection, keyed by session_id.
	Connect(grpc.BidiStreamingServer[AgentMessage, GatewayMessage]) error
	// Bootstrap mTLS: exchange a one-time enrollment token + CSR for a signed client cert.
	// Called over a server-TLS channel (no client cert yet). Single-use; the returned cert's
	// SAN binds the agent's tenant/agent identity for all later Connect calls.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// Cheap unary check the agent SHOULD call before opening the full Connect stream, mirroring
	// curlix.connector.v1.ConnectorGateway.PreConnect — see that RPC's comment and
	// docs/design/skybridge-masking-architecture.md §10.
	PreConnect(context.Context, *PreConnectRequest) (*PreConnectResponse, error)
	mustEmbedUnimplementedStudioGatewayServer()
}

// UnimplementedStudioGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStudioGatewayServer struct{}

func (UnimplementedStudioGatewayServer) Connect(grpc.BidiStreamingServer[AgentMessage, GatewayMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedStudioGatewayServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedStudioGatewayServer) PreConnect(context.Context, *PreConnectRequest) (*PreConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreConnect not implemented")
}
func (UnimplementedStudioGatewayServer) mustEmbedUnimplementedStudioGatewayServer() {}
func (UnimplementedStudioGatewayServer) testEmbeddedByValue()                       {}

// UnsafeStudioGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudioGatewayServer will
// result in compilation errors.
type UnsafeStudioGatewayServer interface {
	mustEmbedUnimplementedStudioGatewayServer()
}

func RegisterStudioGatewayServer(s grpc.ServiceRegistrar, srv StudioGatewayServer) {
	// If the following call panics, it indicates UnimplementedStudioGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StudioGateway_ServiceDesc, srv)
}

func _StudioGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudioGatewayServer).Connect(&grpc.GenericServerStream[AgentMessage, GatewayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StudioGateway_ConnectServer = grpc.BidiStreamingServer[AgentMessage, GatewayMessage]

func _StudioGateway_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioGatewayServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudioGateway_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioGatewayServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudioGateway_PreConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioGatewayServer).PreConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudioGateway_PreConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioGatewayServer).PreConnect(ctx, req.(*PreConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudioGateway_ServiceDesc is the grpc.ServiceDesc for StudioGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudioGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "curlix.studiogateway.v1.StudioGateway",
	HandlerType: (*StudioGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _StudioGateway_Enroll_Handler,
		},
		{
			MethodName: "PreConnect",
			Handler:    _StudioGateway_PreConnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _StudioGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "curlix/studiogateway/v1/studio_gateway.proto",
}
