// Call-home (connection-reversal) contract for a Curlix Studio Agent.
//
// WHY THIS SHAPE: a Studio Agent runs next to the database (typically inside the customer network,
// egress-only). It must NOT expose an inbound port. So the agent DIALS OUT to the SaaS Studio
// Gateway and holds a single long-lived bidirectional stream open. The gateway leases query-execution
// sessions and pushes ExecuteAssignments DOWN that already-open stream; the agent runs the query
// locally (the DB connection never leaves the customer network), redacts PII locally, and streams
// SessionEvents (progress, redacted rows, result, audit) back UP. Many concurrent sessions multiplex
// over the one connection, keyed by session_id.
//
// This is the transport for the Studio execution tier (see docs/design/studio-agent-gateway.md).
// It deliberately mirrors curlix.connector.v1 (connection reversal + mTLS enrollment) and reuses the
// event-stream style of curlix.agent.v1 (terminal *_finished carries the canonical response JSON).
//
// Transport: mTLS is the hardened path. The agent first calls `Enroll` over a server-TLS channel with
// a one-time enrollment token to obtain a client certificate whose SAN encodes its identity
// (spiffe://curlix.studio-agent/tenant/<tenant>/agent/<id>), then opens `Connect` with that client
// cert. Bearer-token-over-edge-TLS remains supported for non-mTLS deployments. The browser never
// speaks this — the SaaS FastAPI app bridges live sessions to the UI over SSE / poll under /api/v1.
//
// CONTRACT: this is a versioned service boundary (the Studio Gateway API). The `v1` in the package is
// part of the wire identity. Only backward-compatible (additive) changes are allowed within `v1`;
// field numbers are permanent (use `reserved` when removing one); breaking changes go in a new
// `curlix.studiogateway.v2` package served alongside `v1`. CI (`buf breaking`) enforces this.
// See proto/README.md.
//
// Regenerate Python stubs with: scripts/gen_agent_grpc.sh

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: curlix/studiogateway/v1/studio_gateway.proto

package studiogatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // one-time secret minted by an operator
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                      // must match the token's bound tenant
	AgentId         string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                         // must match the token's bound agent
	CsrPem          string                 `protobuf:"bytes,4,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                            // PEM-encoded PKCS#10 CSR (agent keeps the private key)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem string                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // signed leaf cert (identity in SAN URI)
	CaBundlePem   string                 `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`       // CA chain the agent trusts for the gateway
	NotAfterUnix  int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`   // cert expiry (agent re-enrolls before this)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *EnrollResponse) GetCaBundlePem() string {
	if x != nil {
		return x.CaBundlePem
	}
	return ""
}

func (x *EnrollResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        string                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // fresh CSR for a new keypair; identity comes from the mTLS channel's
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RenewRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem string                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // freshly signed leaf cert (same identity as the calling cert)
	CaBundlePem   string                 `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`       // CA chain the agent trusts for the gateway
	NotAfterUnix  int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`   // new cert expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RenewResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *RenewResponse) GetCaBundlePem() string {
	if x != nil {
		return x.CaBundlePem
	}
	return ""
}

func (x *RenewResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

// Identity fields mirror Register; see curlix.connector.v1.PreConnectRequest's comment.
type PreConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreConnectRequest) Reset() {
	*x = PreConnectRequest{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreConnectRequest) ProtoMessage() {}

func (x *PreConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreConnectRequest.ProtoReflect.Descriptor instead.
func (*PreConnectRequest) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PreConnectRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PreConnectRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PreConnectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                          // true: proceed to Connect now
	RetryAfterSeconds int32                  `protobuf:"varint,2,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"` // when ok=false, how long to wait before asking again
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                   // human-readable (e.g. "gateway draining", "identity revoked")
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreConnectResponse) Reset() {
	*x = PreConnectResponse{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreConnectResponse) ProtoMessage() {}

func (x *PreConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreConnectResponse.ProtoReflect.Descriptor instead.
func (*PreConnectResponse) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *PreConnectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PreConnectResponse) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *PreConnectResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A target this agent can reach. The gateway routes ExecuteAssignments to an agent whose declared
// bindings cover the requested (db_type, aws_account_id, database_name).
type TargetBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`                     // postgres | mysql | mongodb | snowflake | ...
	AwsAccountId  string                 `protobuf:"bytes,2,opt,name=aws_account_id,json=awsAccountId,proto3" json:"aws_account_id,omitempty"` // scope id (or "env"); empty = any
	DatabaseName  string                 `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`   // empty = any database on that scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetBinding) Reset() {
	*x = TargetBinding{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetBinding) ProtoMessage() {}

func (x *TargetBinding) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetBinding.ProtoReflect.Descriptor instead.
func (*TargetBinding) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TargetBinding) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *TargetBinding) GetAwsAccountId() string {
	if x != nil {
		return x.AwsAccountId
	}
	return ""
}

func (x *TargetBinding) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

// Resolved caller identity. The SaaS authenticates the human (cookie/bearer) and passes the
// already-resolved principal here; the agent does NOT re-run user auth, it trusts this internal
// envelope (the channel itself is service-authenticated). Mirrors curlix.agent.v1.AgentIdentity.
type ExecuteIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	AwsAccountId   string                 `protobuf:"bytes,4,opt,name=aws_account_id,json=awsAccountId,proto3" json:"aws_account_id,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteIdentity) Reset() {
	*x = ExecuteIdentity{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteIdentity) ProtoMessage() {}

func (x *ExecuteIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteIdentity.ProtoReflect.Descriptor instead.
func (*ExecuteIdentity) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExecuteIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExecuteIdentity) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ExecuteIdentity) GetAwsAccountId() string {
	if x != nil {
		return x.AwsAccountId
	}
	return ""
}

func (x *ExecuteIdentity) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// A Studio execution request. Mirrors the SaaS StudioExecuteParams. apply_pii_redaction is an
// instruction the agent MUST honor BEFORE rows leave the customer network — raw PII never crosses
// this wire. The SaaS resolves catalog-backed PII policy before assignment and sends a decided flag.
type ExecuteRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DbType                  string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	AwsAccountId            string                 `protobuf:"bytes,2,opt,name=aws_account_id,json=awsAccountId,proto3" json:"aws_account_id,omitempty"`
	DatabaseName            string                 `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	QueryContent            string                 `protobuf:"bytes,4,opt,name=query_content,json=queryContent,proto3" json:"query_content,omitempty"`
	MongoConnectionRole     string                 `protobuf:"bytes,5,opt,name=mongo_connection_role,json=mongoConnectionRole,proto3" json:"mongo_connection_role,omitempty"`
	SnowflakeConnectionRole string                 `protobuf:"bytes,6,opt,name=snowflake_connection_role,json=snowflakeConnectionRole,proto3" json:"snowflake_connection_role,omitempty"`
	ApplyPiiRedaction       bool                   `protobuf:"varint,7,opt,name=apply_pii_redaction,json=applyPiiRedaction,proto3" json:"apply_pii_redaction,omitempty"`
	CatalogTemplateName     string                 `protobuf:"bytes,8,opt,name=catalog_template_name,json=catalogTemplateName,proto3" json:"catalog_template_name,omitempty"`
	DryRun                  bool                   `protobuf:"varint,9,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *ExecuteRequest) GetAwsAccountId() string {
	if x != nil {
		return x.AwsAccountId
	}
	return ""
}

func (x *ExecuteRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *ExecuteRequest) GetQueryContent() string {
	if x != nil {
		return x.QueryContent
	}
	return ""
}

func (x *ExecuteRequest) GetMongoConnectionRole() string {
	if x != nil {
		return x.MongoConnectionRole
	}
	return ""
}

func (x *ExecuteRequest) GetSnowflakeConnectionRole() string {
	if x != nil {
		return x.SnowflakeConnectionRole
	}
	return ""
}

func (x *ExecuteRequest) GetApplyPiiRedaction() bool {
	if x != nil {
		return x.ApplyPiiRedaction
	}
	return false
}

func (x *ExecuteRequest) GetCatalogTemplateName() string {
	if x != nil {
		return x.CatalogTemplateName
	}
	return ""
}

func (x *ExecuteRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`           // organization id this agent serves
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`              // stable agent instance id
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                             // agent build version (upgrade/telemetry)
	Targets       []*TargetBinding       `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`                             // databases/scopes this agent can reach
	MaxSessions   int32                  `protobuf:"varint,5,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"` // local concurrency capacity (agent-side admission)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Register) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Register) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetTargets() []*TargetBinding {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Register) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UnixMillis     int64                  `protobuf:"varint,1,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"` // current local load; feeds gateway leasing + autoscaling gauges
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *Heartbeat) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

// Lease accept/reject for an assigned session. The agent's own admission check — the agent-side
// twin of the SaaS Phase-1 studio_sessions_busy backpressure.
type SessionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // when accepted=false (e.g. "agent_at_capacity", "no_driver")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAck) Reset() {
	*x = SessionAck{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAck) ProtoMessage() {}

func (x *SessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAck.ProtoReflect.Descriptor instead.
func (*SessionAck) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *SessionAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// One execution event produced by an assigned session, tagged with its session_id.
type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Event         *ExecuteEvent          `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetEvent() *ExecuteEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_SessionAck
	//	*AgentMessage_SessionEvent
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetSessionAck() *SessionAck {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_SessionAck); ok {
			return x.SessionAck
		}
	}
	return nil
}

func (x *AgentMessage) GetSessionEvent() *SessionEvent {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_SessionEvent); ok {
			return x.SessionEvent
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_SessionAck struct {
	SessionAck *SessionAck `protobuf:"bytes,3,opt,name=session_ack,json=sessionAck,proto3,oneof"`
}

type AgentMessage_SessionEvent struct {
	SessionEvent *SessionEvent `protobuf:"bytes,4,opt,name=session_event,json=sessionEvent,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_SessionAck) isAgentMessage_Msg() {}

func (*AgentMessage_SessionEvent) isAgentMessage_Msg() {}

type Registered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"` // identifies this agent's registration lease for the connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *Registered) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// "Run this Studio session." Carries the resolved request + identity, a hard deadline, and the
// idempotency key so a redelivered assignment is de-duplicated agent-side.
type ExecuteAssignment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Request            *ExecuteRequest        `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Identity           *ExecuteIdentity       `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	DeadlineUnixMillis int64                  `protobuf:"varint,4,opt,name=deadline_unix_millis,json=deadlineUnixMillis,proto3" json:"deadline_unix_millis,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteAssignment) Reset() {
	*x = ExecuteAssignment{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteAssignment) ProtoMessage() {}

func (x *ExecuteAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteAssignment.ProtoReflect.Descriptor instead.
func (*ExecuteAssignment) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteAssignment) GetRequest() *ExecuteRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteAssignment) GetIdentity() *ExecuteIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ExecuteAssignment) GetDeadlineUnixMillis() int64 {
	if x != nil {
		return x.DeadlineUnixMillis
	}
	return 0
}

func (x *ExecuteAssignment) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// Cancel an in-flight session. The wire form of the SaaS durable cross-replica cancel.
type CancelSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSession) Reset() {
	*x = CancelSession{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSession) ProtoMessage() {}

func (x *CancelSession) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSession.ProtoReflect.Descriptor instead.
func (*CancelSession) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *CancelSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelSession) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMillis    int64                  `protobuf:"varint,1,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *Ping) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

type GatewayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GatewayMessage_Registered
	//	*GatewayMessage_ExecuteAssignment
	//	*GatewayMessage_CancelSession
	//	*GatewayMessage_Ping
	Msg           isGatewayMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *GatewayMessage) GetMsg() isGatewayMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GatewayMessage) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *GatewayMessage) GetExecuteAssignment() *ExecuteAssignment {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_ExecuteAssignment); ok {
			return x.ExecuteAssignment
		}
	}
	return nil
}

func (x *GatewayMessage) GetCancelSession() *CancelSession {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_CancelSession); ok {
			return x.CancelSession
		}
	}
	return nil
}

func (x *GatewayMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isGatewayMessage_Msg interface {
	isGatewayMessage_Msg()
}

type GatewayMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type GatewayMessage_ExecuteAssignment struct {
	ExecuteAssignment *ExecuteAssignment `protobuf:"bytes,2,opt,name=execute_assignment,json=executeAssignment,proto3,oneof"`
}

type GatewayMessage_CancelSession struct {
	CancelSession *CancelSession `protobuf:"bytes,3,opt,name=cancel_session,json=cancelSession,proto3,oneof"`
}

type GatewayMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*GatewayMessage_Registered) isGatewayMessage_Msg() {}

func (*GatewayMessage_ExecuteAssignment) isGatewayMessage_Msg() {}

func (*GatewayMessage_CancelSession) isGatewayMessage_Msg() {}

func (*GatewayMessage_Ping) isGatewayMessage_Msg() {}

// Session accepted and execution has begun.
type SessionStarted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartedUnixMillis int64                  `protobuf:"varint,1,opt,name=started_unix_millis,json=startedUnixMillis,proto3" json:"started_unix_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionStarted) Reset() {
	*x = SessionStarted{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStarted) ProtoMessage() {}

func (x *SessionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStarted.ProtoReflect.Descriptor instead.
func (*SessionStarted) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *SessionStarted) GetStartedUnixMillis() int64 {
	if x != nil {
		return x.StartedUnixMillis
	}
	return 0
}

// Coarse progress for live UX. status is a free-form string (e.g. "connecting", "executing",
// "redacting"), consistent with curlix.agent.v1.StepEvent.status.
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RowsSoFar     int64                  `protobuf:"varint,3,opt,name=rows_so_far,json=rowsSoFar,proto3" json:"rows_so_far,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *Progress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetRowsSoFar() int64 {
	if x != nil {
		return x.RowsSoFar
	}
	return 0
}

// A chunk of (already PII-redacted) result rows. columns_json is sent on the first batch only;
// rows_json is a JSON-encoded array of rows. last=true marks the final batch.
type RowBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnsJson   string                 `protobuf:"bytes,1,opt,name=columns_json,json=columnsJson,proto3" json:"columns_json,omitempty"`
	RowsJson      string                 `protobuf:"bytes,2,opt,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowBatch) Reset() {
	*x = RowBatch{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowBatch) ProtoMessage() {}

func (x *RowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowBatch.ProtoReflect.Descriptor instead.
func (*RowBatch) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *RowBatch) GetColumnsJson() string {
	if x != nil {
		return x.ColumnsJson
	}
	return ""
}

func (x *RowBatch) GetRowsJson() string {
	if x != nil {
		return x.RowsJson
	}
	return ""
}

func (x *RowBatch) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// Terminal success. Carries the full canonical execute response as JSON so the SaaS reconstructs the
// exact same structured result the REST /execute endpoint returns. Mirrors curlix.agent.v1.RunFinished.
type ResultFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseJson  string                 `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultFinished) Reset() {
	*x = ResultFinished{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultFinished) ProtoMessage() {}

func (x *ResultFinished) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultFinished.ProtoReflect.Descriptor instead.
func (*ResultFinished) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *ResultFinished) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

// Terminal failure. code/query_hash mirror the SaaS structured-error envelope.
type ExecuteError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	QueryHash     string                 `protobuf:"bytes,3,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteError) Reset() {
	*x = ExecuteError{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteError) ProtoMessage() {}

func (x *ExecuteError) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteError.ProtoReflect.Descriptor instead.
func (*ExecuteError) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteError) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

type ExecuteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteEvent_Started
	//	*ExecuteEvent_Progress
	//	*ExecuteEvent_RowBatch
	//	*ExecuteEvent_Finished
	//	*ExecuteEvent_Error
	Event         isExecuteEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *ExecuteEvent) GetEvent() isExecuteEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteEvent) GetStarted() *SessionStarted {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ExecuteEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExecuteEvent) GetRowBatch() *RowBatch {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_RowBatch); ok {
			return x.RowBatch
		}
	}
	return nil
}

func (x *ExecuteEvent) GetFinished() *ResultFinished {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

func (x *ExecuteEvent) GetError() *ExecuteError {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isExecuteEvent_Event interface {
	isExecuteEvent_Event()
}

type ExecuteEvent_Started struct {
	Started *SessionStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type ExecuteEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type ExecuteEvent_RowBatch struct {
	RowBatch *RowBatch `protobuf:"bytes,3,opt,name=row_batch,json=rowBatch,proto3,oneof"`
}

type ExecuteEvent_Finished struct {
	Finished *ResultFinished `protobuf:"bytes,4,opt,name=finished,proto3,oneof"`
}

type ExecuteEvent_Error struct {
	Error *ExecuteError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ExecuteEvent_Started) isExecuteEvent_Event() {}

func (*ExecuteEvent_Progress) isExecuteEvent_Event() {}

func (*ExecuteEvent_RowBatch) isExecuteEvent_Event() {}

func (*ExecuteEvent_Finished) isExecuteEvent_Event() {}

func (*ExecuteEvent_Error) isExecuteEvent_Event() {}

var File_curlix_studiogateway_v1_studio_gateway_proto protoreflect.FileDescriptor

const file_curlix_studiogateway_v1_studio_gateway_proto_rawDesc = "" +
	"\n" +
	",curlix/studiogateway/v1/studio_gateway.proto\x12\x17curlix.studiogateway.v1\"\x8b\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\acsr_pem\x18\x04 \x01(\tR\x06csrPem\"\x82\x01\n" +
	"\x0eEnrollResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\tR\rclientCertPem\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\tR\vcaBundlePem\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\"'\n" +
	"\fRenewRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\"\x81\x01\n" +
	"\rRenewResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\tR\rclientCertPem\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\tR\vcaBundlePem\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\"K\n" +
	"\x11PreConnectRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"l\n" +
	"\x12PreConnectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12.\n" +
	"\x13retry_after_seconds\x18\x02 \x01(\x05R\x11retryAfterSeconds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"s\n" +
	"\rTargetBinding\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12$\n" +
	"\x0eaws_account_id\x18\x02 \x01(\tR\fawsAccountId\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\"\xb9\x01\n" +
	"\x0fExecuteIdentity\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0eaws_account_id\x18\x04 \x01(\tR\fawsAccountId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x86\x03\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12$\n" +
	"\x0eaws_account_id\x18\x02 \x01(\tR\fawsAccountId\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\x12#\n" +
	"\rquery_content\x18\x04 \x01(\tR\fqueryContent\x122\n" +
	"\x15mongo_connection_role\x18\x05 \x01(\tR\x13mongoConnectionRole\x12:\n" +
	"\x19snowflake_connection_role\x18\x06 \x01(\tR\x17snowflakeConnectionRole\x12.\n" +
	"\x13apply_pii_redaction\x18\a \x01(\bR\x11applyPiiRedaction\x122\n" +
	"\x15catalog_template_name\x18\b \x01(\tR\x13catalogTemplateName\x12\x17\n" +
	"\adry_run\x18\t \x01(\bR\x06dryRun\"\xc1\x01\n" +
	"\bRegister\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12@\n" +
	"\atargets\x18\x04 \x03(\v2&.curlix.studiogateway.v1.TargetBindingR\atargets\x12!\n" +
	"\fmax_sessions\x18\x05 \x01(\x05R\vmaxSessions\"U\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vunix_millis\x18\x01 \x01(\x03R\n" +
	"unixMillis\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\"_\n" +
	"\n" +
	"SessionAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"j\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\x05event\x18\x02 \x01(\v2%.curlix.studiogateway.v1.ExecuteEventR\x05event\"\xb0\x02\n" +
	"\fAgentMessage\x12?\n" +
	"\bregister\x18\x01 \x01(\v2!.curlix.studiogateway.v1.RegisterH\x00R\bregister\x12B\n" +
	"\theartbeat\x18\x02 \x01(\v2\".curlix.studiogateway.v1.HeartbeatH\x00R\theartbeat\x12F\n" +
	"\vsession_ack\x18\x03 \x01(\v2#.curlix.studiogateway.v1.SessionAckH\x00R\n" +
	"sessionAck\x12L\n" +
	"\rsession_event\x18\x04 \x01(\v2%.curlix.studiogateway.v1.SessionEventH\x00R\fsessionEventB\x05\n" +
	"\x03msg\"'\n" +
	"\n" +
	"Registered\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x96\x02\n" +
	"\x11ExecuteAssignment\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.curlix.studiogateway.v1.ExecuteRequestR\arequest\x12D\n" +
	"\bidentity\x18\x03 \x01(\v2(.curlix.studiogateway.v1.ExecuteIdentityR\bidentity\x120\n" +
	"\x14deadline_unix_millis\x18\x04 \x01(\x03R\x12deadlineUnixMillis\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"F\n" +
	"\rCancelSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"'\n" +
	"\x04Ping\x12\x1f\n" +
	"\vunix_millis\x18\x01 \x01(\x03R\n" +
	"unixMillis\"\xc1\x02\n" +
	"\x0eGatewayMessage\x12E\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2#.curlix.studiogateway.v1.RegisteredH\x00R\n" +
	"registered\x12[\n" +
	"\x12execute_assignment\x18\x02 \x01(\v2*.curlix.studiogateway.v1.ExecuteAssignmentH\x00R\x11executeAssignment\x12O\n" +
	"\x0ecancel_session\x18\x03 \x01(\v2&.curlix.studiogateway.v1.CancelSessionH\x00R\rcancelSession\x123\n" +
	"\x04ping\x18\x04 \x01(\v2\x1d.curlix.studiogateway.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"@\n" +
	"\x0eSessionStarted\x12.\n" +
	"\x13started_unix_millis\x18\x01 \x01(\x03R\x11startedUnixMillis\"\\\n" +
	"\bProgress\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\vrows_so_far\x18\x03 \x01(\x03R\trowsSoFar\"^\n" +
	"\bRowBatch\x12!\n" +
	"\fcolumns_json\x18\x01 \x01(\tR\vcolumnsJson\x12\x1b\n" +
	"\trows_json\x18\x02 \x01(\tR\browsJson\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"5\n" +
	"\x0eResultFinished\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\tR\fresponseJson\"[\n" +
	"\fExecuteError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x03 \x01(\tR\tqueryHash\"\xe5\x02\n" +
	"\fExecuteEvent\x12C\n" +
	"\astarted\x18\x01 \x01(\v2'.curlix.studiogateway.v1.SessionStartedH\x00R\astarted\x12?\n" +
	"\bprogress\x18\x02 \x01(\v2!.curlix.studiogateway.v1.ProgressH\x00R\bprogress\x12@\n" +
	"\trow_batch\x18\x03 \x01(\v2!.curlix.studiogateway.v1.RowBatchH\x00R\browBatch\x12E\n" +
	"\bfinished\x18\x04 \x01(\v2'.curlix.studiogateway.v1.ResultFinishedH\x00R\bfinished\x12=\n" +
	"\x05error\x18\x05 \x01(\v2%.curlix.studiogateway.v1.ExecuteErrorH\x00R\x05errorB\a\n" +
	"\x05event2\x88\x03\n" +
	"\rStudioGateway\x12]\n" +
	"\aConnect\x12%.curlix.studiogateway.v1.AgentMessage\x1a'.curlix.studiogateway.v1.GatewayMessage(\x010\x01\x12Y\n" +
	"\x06Enroll\x12&.curlix.studiogateway.v1.EnrollRequest\x1a'.curlix.studiogateway.v1.EnrollResponse\x12e\n" +
	"\n" +
	"PreConnect\x12*.curlix.studiogateway.v1.PreConnectRequest\x1a+.curlix.studiogateway.v1.PreConnectResponse\x12V\n" +
	"\x05Renew\x12%.curlix.studiogateway.v1.RenewRequest\x1a&.curlix.studiogateway.v1.RenewResponseB\x86\x02\n" +
	"\x1bcom.curlix.studiogateway.v1B\x12StudioGatewayProtoP\x01ZUgithub.com/curlix-io/skybridge/internal/genpb/curlix/studiogateway/v1;studiogatewayv1\xa2\x02\x03CSX\xaa\x02\x17Curlix.Studiogateway.V1\xca\x02\x17Curlix\\Studiogateway\\V1\xe2\x02#Curlix\\Studiogateway\\V1\\GPBMetadata\xea\x02\x19Curlix::Studiogateway::V1b\x06proto3"

var (
	file_curlix_studiogateway_v1_studio_gateway_proto_rawDescOnce sync.Once
	file_curlix_studiogateway_v1_studio_gateway_proto_rawDescData []byte
)

func file_curlix_studiogateway_v1_studio_gateway_proto_rawDescGZIP() []byte {
	file_curlix_studiogateway_v1_studio_gateway_proto_rawDescOnce.Do(func() {
		file_curlix_studiogateway_v1_studio_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_curlix_studiogateway_v1_studio_gateway_proto_rawDesc), len(file_curlix_studiogateway_v1_studio_gateway_proto_rawDesc)))
	})
	return file_curlix_studiogateway_v1_studio_gateway_proto_rawDescData
}

var file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_curlix_studiogateway_v1_studio_gateway_proto_goTypes = []any{
	(*EnrollRequest)(nil),      // 0: curlix.studiogateway.v1.EnrollRequest
	(*EnrollResponse)(nil),     // 1: curlix.studiogateway.v1.EnrollResponse
	(*RenewRequest)(nil),       // 2: curlix.studiogateway.v1.RenewRequest
	(*RenewResponse)(nil),      // 3: curlix.studiogateway.v1.RenewResponse
	(*PreConnectRequest)(nil),  // 4: curlix.studiogateway.v1.PreConnectRequest
	(*PreConnectResponse)(nil), // 5: curlix.studiogateway.v1.PreConnectResponse
	(*TargetBinding)(nil),      // 6: curlix.studiogateway.v1.TargetBinding
	(*ExecuteIdentity)(nil),    // 7: curlix.studiogateway.v1.ExecuteIdentity
	(*ExecuteRequest)(nil),     // 8: curlix.studiogateway.v1.ExecuteRequest
	(*Register)(nil),           // 9: curlix.studiogateway.v1.Register
	(*Heartbeat)(nil),          // 10: curlix.studiogateway.v1.Heartbeat
	(*SessionAck)(nil),         // 11: curlix.studiogateway.v1.SessionAck
	(*SessionEvent)(nil),       // 12: curlix.studiogateway.v1.SessionEvent
	(*AgentMessage)(nil),       // 13: curlix.studiogateway.v1.AgentMessage
	(*Registered)(nil),         // 14: curlix.studiogateway.v1.Registered
	(*ExecuteAssignment)(nil),  // 15: curlix.studiogateway.v1.ExecuteAssignment
	(*CancelSession)(nil),      // 16: curlix.studiogateway.v1.CancelSession
	(*Ping)(nil),               // 17: curlix.studiogateway.v1.Ping
	(*GatewayMessage)(nil),     // 18: curlix.studiogateway.v1.GatewayMessage
	(*SessionStarted)(nil),     // 19: curlix.studiogateway.v1.SessionStarted
	(*Progress)(nil),           // 20: curlix.studiogateway.v1.Progress
	(*RowBatch)(nil),           // 21: curlix.studiogateway.v1.RowBatch
	(*ResultFinished)(nil),     // 22: curlix.studiogateway.v1.ResultFinished
	(*ExecuteError)(nil),       // 23: curlix.studiogateway.v1.ExecuteError
	(*ExecuteEvent)(nil),       // 24: curlix.studiogateway.v1.ExecuteEvent
}
var file_curlix_studiogateway_v1_studio_gateway_proto_depIdxs = []int32{
	6,  // 0: curlix.studiogateway.v1.Register.targets:type_name -> curlix.studiogateway.v1.TargetBinding
	24, // 1: curlix.studiogateway.v1.SessionEvent.event:type_name -> curlix.studiogateway.v1.ExecuteEvent
	9,  // 2: curlix.studiogateway.v1.AgentMessage.register:type_name -> curlix.studiogateway.v1.Register
	10, // 3: curlix.studiogateway.v1.AgentMessage.heartbeat:type_name -> curlix.studiogateway.v1.Heartbeat
	11, // 4: curlix.studiogateway.v1.AgentMessage.session_ack:type_name -> curlix.studiogateway.v1.SessionAck
	12, // 5: curlix.studiogateway.v1.AgentMessage.session_event:type_name -> curlix.studiogateway.v1.SessionEvent
	8,  // 6: curlix.studiogateway.v1.ExecuteAssignment.request:type_name -> curlix.studiogateway.v1.ExecuteRequest
	7,  // 7: curlix.studiogateway.v1.ExecuteAssignment.identity:type_name -> curlix.studiogateway.v1.ExecuteIdentity
	14, // 8: curlix.studiogateway.v1.GatewayMessage.registered:type_name -> curlix.studiogateway.v1.Registered
	15, // 9: curlix.studiogateway.v1.GatewayMessage.execute_assignment:type_name -> curlix.studiogateway.v1.ExecuteAssignment
	16, // 10: curlix.studiogateway.v1.GatewayMessage.cancel_session:type_name -> curlix.studiogateway.v1.CancelSession
	17, // 11: curlix.studiogateway.v1.GatewayMessage.ping:type_name -> curlix.studiogateway.v1.Ping
	19, // 12: curlix.studiogateway.v1.ExecuteEvent.started:type_name -> curlix.studiogateway.v1.SessionStarted
	20, // 13: curlix.studiogateway.v1.ExecuteEvent.progress:type_name -> curlix.studiogateway.v1.Progress
	21, // 14: curlix.studiogateway.v1.ExecuteEvent.row_batch:type_name -> curlix.studiogateway.v1.RowBatch
	22, // 15: curlix.studiogateway.v1.ExecuteEvent.finished:type_name -> curlix.studiogateway.v1.ResultFinished
	23, // 16: curlix.studiogateway.v1.ExecuteEvent.error:type_name -> curlix.studiogateway.v1.ExecuteError
	13, // 17: curlix.studiogateway.v1.StudioGateway.Connect:input_type -> curlix.studiogateway.v1.AgentMessage
	0,  // 18: curlix.studiogateway.v1.StudioGateway.Enroll:input_type -> curlix.studiogateway.v1.EnrollRequest
	4,  // 19: curlix.studiogateway.v1.StudioGateway.PreConnect:input_type -> curlix.studiogateway.v1.PreConnectRequest
	2,  // 20: curlix.studiogateway.v1.StudioGateway.Renew:input_type -> curlix.studiogateway.v1.RenewRequest
	18, // 21: curlix.studiogateway.v1.StudioGateway.Connect:output_type -> curlix.studiogateway.v1.GatewayMessage
	1,  // 22: curlix.studiogateway.v1.StudioGateway.Enroll:output_type -> curlix.studiogateway.v1.EnrollResponse
	5,  // 23: curlix.studiogateway.v1.StudioGateway.PreConnect:output_type -> curlix.studiogateway.v1.PreConnectResponse
	3,  // 24: curlix.studiogateway.v1.StudioGateway.Renew:output_type -> curlix.studiogateway.v1.RenewResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_curlix_studiogateway_v1_studio_gateway_proto_init() }
func file_curlix_studiogateway_v1_studio_gateway_proto_init() {
	if File_curlix_studiogateway_v1_studio_gateway_proto != nil {
		return
	}
	file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[13].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_SessionAck)(nil),
		(*AgentMessage_SessionEvent)(nil),
	}
	file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[18].OneofWrappers = []any{
		(*GatewayMessage_Registered)(nil),
		(*GatewayMessage_ExecuteAssignment)(nil),
		(*GatewayMessage_CancelSession)(nil),
		(*GatewayMessage_Ping)(nil),
	}
	file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes[24].OneofWrappers = []any{
		(*ExecuteEvent_Started)(nil),
		(*ExecuteEvent_Progress)(nil),
		(*ExecuteEvent_RowBatch)(nil),
		(*ExecuteEvent_Finished)(nil),
		(*ExecuteEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_curlix_studiogateway_v1_studio_gateway_proto_rawDesc), len(file_curlix_studiogateway_v1_studio_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_curlix_studiogateway_v1_studio_gateway_proto_goTypes,
		DependencyIndexes: file_curlix_studiogateway_v1_studio_gateway_proto_depIdxs,
		MessageInfos:      file_curlix_studiogateway_v1_studio_gateway_proto_msgTypes,
	}.Build()
	File_curlix_studiogateway_v1_studio_gateway_proto = out.File
	file_curlix_studiogateway_v1_studio_gateway_proto_goTypes = nil
	file_curlix_studiogateway_v1_studio_gateway_proto_depIdxs = nil
}
